### ISSUE TITLE
What about other Axios options

### ISSUE THREAD

**Issue by shubham399** [iarthstar/purescript-axios#1]
https://github.com/iarthstar/purescript-axios/blob/d3f060d5d262900092daefb6e16028d70d967381/src/Axios.purs#L32
Like timeout, clientCert etc

**Comment by iarthstar** [comment]
WIP on axios options, would be a great help, if you can share more requirements as such...

**Comment by iarthstar** [comment]
I have refactored the definitions and changed Config res to Array Config. So now you generate a Config using helper functions i.e. method, headers, auth, timeout etc.
```purescript
genericAxios "/req_res/users/9" 
  [ method GET
  , headers [ Header "Content-Type" "application/json" ]
  , baseUrl "https://grandeur-backend.herokuapp.com"
  , auth "1234" "1234"
  , timeout 1000
  ] req
```
